name: my_money
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  dartz: ^0.9.2
  datetime_picker_formfield: ^1.0.0
  flushbar: ^1.10.4
  flutter_colorpicker: ^0.3.4
  flutter_iconpicker: ^2.2.2
  flutter_masked_text: ^0.8.0
  flutter_slidable: ^0.5.7
  intl: ^0.16.1
  path: ^1.7.0
  path_provider: ^1.6.24
  sembast: ^2.4.8
  fl_chart: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
